background{
	monitor =
	path = /home/mouse/Downloads/Guts.png
	blur_passes = 2
	blur_size = 8
}

general {
	hide_cursor = true
}


label {
	monitor =
	text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
	font_size = 80
	font_family = SF Pro Display Bold
	color = rgba(255, 255, 255, 0.75)
	halign = right
	valign = top
}

label {
	monitor = 
	text = cmd[update:60000] echo "$(date +"%A, %d, %B, %Y")"
	font_size = 18
	font_family = SF Pro Display Bold
	color = rgba(135, 135, 135, 0.35)
	halign = right
	valign = top
	position = 0, -115
}

input-field {
	monitor = 
	size = 300, 55
	halign = center
	valign = center

	outer_color = rgba(255, 255, 255, 0.35)	
	inner_color = rgba(255, 255, 255, 0.12)
	rounding = 5
	outline_thickness = 0

	font_family = Noto Sans
	placeholder_text = <span foreground="##969393">Password</span>

	dots_size = 0.15
	dots_center = true
	dots_text_format = <span foreground="##ffffff">●</span>

#	fail_color = rgba(220, 50, 47, 0.12)
#	fail_transition = 180
#	fail_timeout = 1200
	fail_text = 

	hide_input = false
	fade_on_empty = false
}

#---------------------------------------------------

image {
	monitor = 
	path = "/home/mouse/Downloads/c.jpg"
	border_size = 0
	size = 150
	rounding = -1
	halign = center
	valign = center
	position = 0, 150
	
}

#---------------------------------------------------

label {
    text = $LAYOUT
    font_size = 12
    color = rgba(200, 200, 200, 0.6)

    position = 0, 40
    halign = center
    valign = bottom
}

