#############
### INPUT ###
#############

input {
    kb_layout = us, ua
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =

    numlock_by_default = true
    accel_profile = adaptive
    follow_mouse = 0

    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

group {
    auto_group = true
    insert_after_current = false
    drag_into_group = 1

    groupbar {
        enabled = true
        font_size = 15
    }
}
